services:
  postgres:
    image: postgres:15-alpine
    container_name: rfm_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-rfm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rfm_password}
      POSTGRES_DB: ${DB_NAME:-rfm_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-rfm_user} -d ${DB_NAME:-rfm_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    container_name: rfm_airflow_init
    environment:
      - AIRFLOW_HOME=/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${DB_USER:-rfm_user}:${DB_PASSWORD:-rfm_password}@postgres:5432/${DB_NAME:-rfm_db}
      - DB_USER=${DB_USER:-rfm_user}
      - DB_NAME=${DB_NAME:-rfm_db}
    depends_on:
      postgres:
        condition: service_healthy
    # On intègre le script directement ici pour contourner les erreurs de format Windows (CRLF) [cite: 9, 16, 57]
    command: >
      bash -c " echo '⏳ Attente de PostgreSQL...' && until pg_isready -h postgres -U $$DB_USER -d $$DB_NAME; do sleep 1; done && echo '🔧 Migration de la base...' && airflow db migrate && echo '👤 Création de l utilisateur admin...' && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com 2>/dev/null || echo 'L utilisateur existe deja' "

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    container_name: rfm_airflow_webserver
    restart: always
    environment:
      - AIRFLOW_HOME=/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${DB_USER:-rfm_user}:${DB_PASSWORD:-rfm_password}@postgres:5432/${DB_NAME:-rfm_db}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-rfm_db}
      - DB_USER=${DB_USER:-rfm_user}
      - DB_PASSWORD=${DB_PASSWORD:-rfm_password}
    ports:
      - "8080:8080"
    volumes:
      - airflow_home:/airflow
      - ./src/dags:/airflow/dags
      - ./src/etl:/airflow/etl
      - ./data:/airflow/data
      - ./config:/airflow/config
      - ./airflow/logs:/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    # Commande épurée : on ne fait que lancer le webserver
    command: bash -c "airflow webserver"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    container_name: rfm_airflow_scheduler
    restart: always
    environment:
      - AIRFLOW_HOME=/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${DB_USER:-rfm_user}:${DB_PASSWORD:-rfm_password}@postgres:5432/${DB_NAME:-rfm_db}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-rfm_db}
      - DB_USER=${DB_USER:-rfm_user}
      - DB_PASSWORD=${DB_PASSWORD:-rfm_password}
    volumes:
      - airflow_home:/airflow
      - ./src/dags:/airflow/dags
      - ./src/etl:/airflow/etl
      - ./data:/airflow/data
      - ./config:/airflow/config
      - ./airflow/logs:/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    # Commande épurée : on ne fait que lancer le scheduler
    command: bash -c "airflow scheduler"

  pgadmin:
    image: dpage/pgadmin4
    container_name: rfm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rfm_streamlit
    entrypoint: []
    ports:
      - "8501:8501"
    environment:
      - DB_URL=postgresql://rfm_user:rfm_password@postgres:5432/rfm_db
    volumes:
      - ./src/app:/app
    working_dir: /app
    command: >
      bash -c "python3 -m streamlit run main.py --server.port 8501 --server.address 0.0.0.0"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  airflow_home:
